services:
  db:
    image: postgres:13.5
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: cfptest
      POSTGRES_USER: cfpuser
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/rates.sql:/docker-entrypoint-initdb.d/rates.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rates-api
    environment:
      DATABASE_CONNECTION_STRING: postgres://cfpuser@db:5432/cfptest
    ports:
      - "3000:3000"
    depends_on:
          db:
            condition: service_healthy
            restart: true
